ALTER TABLE public.licenses
  ADD COLUMN IF NOT EXISTS customer_phone text,
  ADD COLUMN IF NOT EXISTS admin_note text;

ALTER TABLE public.licenses
  ADD CONSTRAINT licenses_customer_phone_length CHECK (customer_phone IS NULL OR char_length(customer_phone) <= 30),
  ADD CONSTRAINT licenses_admin_note_length CHECK (admin_note IS NULL OR char_length(admin_note) <= 1000);

CREATE TABLE public.license_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_id bigint REFERENCES public.licenses(id) ON DELETE SET NULL,
  admin_user_id uuid NOT NULL,
  action text NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.license_audit_logs TO authenticated;
GRANT ALL ON public.license_audit_logs TO service_role;
ALTER TABLE public.license_audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can read license audit logs"
  ON public.license_audit_logs FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can create license audit logs"
  ON public.license_audit_logs FOR INSERT TO authenticated
  WITH CHECK (public.has_role(auth.uid(), 'admin') AND admin_user_id = auth.uid());

CREATE INDEX license_audit_logs_license_created_idx
  ON public.license_audit_logs (license_id, created_at DESC);

CREATE TABLE public.extension_rate_limits (
  fingerprint text PRIMARY KEY,
  window_started_at timestamptz NOT NULL DEFAULT now(),
  request_count integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON public.extension_rate_limits TO service_role;
ALTER TABLE public.extension_rate_limits ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.license_devices
  ADD COLUMN IF NOT EXISTS trial_license_id bigint REFERENCES public.licenses(id) ON DELETE SET NULL;
CREATE UNIQUE INDEX IF NOT EXISTS license_devices_trial_device_unique
  ON public.license_devices (device_id)
  WHERE trial_license_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.claim_license_device(
  _license_id bigint,
  _device_id text,
  _label text,
  _wa_number text,
  _max_devices integer
)
RETURNS TABLE(device_row_id uuid, device_count bigint, created boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  existing_id uuid;
  inserted_id uuid;
  used_count bigint;
BEGIN
  IF char_length(_device_id) < 6 OR char_length(_device_id) > 120 THEN
    RAISE EXCEPTION 'invalid_device_id';
  END IF;

  PERFORM pg_advisory_xact_lock(_license_id);

  SELECT id INTO existing_id
  FROM public.license_devices
  WHERE license_id = _license_id AND device_id = _device_id;

  IF existing_id IS NOT NULL THEN
    UPDATE public.license_devices
      SET last_seen = now(),
          label = COALESCE(_label, label),
          wa_number = COALESCE(_wa_number, wa_number)
      WHERE id = existing_id;
    SELECT count(*) INTO used_count FROM public.license_devices WHERE license_id = _license_id;
    RETURN QUERY SELECT existing_id, used_count, false;
    RETURN;
  END IF;

  SELECT count(*) INTO used_count FROM public.license_devices WHERE license_id = _license_id;
  IF used_count >= GREATEST(_max_devices, 1) THEN
    RAISE EXCEPTION 'device_limit';
  END IF;

  INSERT INTO public.license_devices (license_id, device_id, label, wa_number)
  VALUES (_license_id, _device_id, _label, _wa_number)
  RETURNING id INTO inserted_id;

  used_count := used_count + 1;
  RETURN QUERY SELECT inserted_id, used_count, true;
END;
$$;
REVOKE ALL ON FUNCTION public.claim_license_device(bigint,text,text,text,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_license_device(bigint,text,text,text,integer) TO service_role;

CREATE OR REPLACE FUNCTION public.consume_extension_rate_limit(
  _fingerprint text,
  _limit integer DEFAULT 30,
  _window_seconds integer DEFAULT 60
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  allowed boolean;
BEGIN
  INSERT INTO public.extension_rate_limits AS r (fingerprint, window_started_at, request_count, updated_at)
  VALUES (_fingerprint, now(), 1, now())
  ON CONFLICT (fingerprint) DO UPDATE SET
    window_started_at = CASE WHEN r.window_started_at < now() - make_interval(secs => _window_seconds) THEN now() ELSE r.window_started_at END,
    request_count = CASE WHEN r.window_started_at < now() - make_interval(secs => _window_seconds) THEN 1 ELSE r.request_count + 1 END,
    updated_at = now()
  RETURNING request_count <= _limit INTO allowed;
  RETURN allowed;
END;
$$;
REVOKE ALL ON FUNCTION public.consume_extension_rate_limit(text,integer,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_extension_rate_limit(text,integer,integer) TO service_role;